export const commonParkedCodes = Object.freeze(['ROLE_CONFIGURATION_INVALID', 'ROLE_HIERARCHY_BLOCKED',
  'BOT_PERMISSION_MISSING', 'DISCORD_AUTHORIZATION_FAILED', 'OPERATION_DENIED', 'MEMBER_ACTION_EPOCH_CHANGED']);
export const caseParkedCodes = Object.freeze(['CASE_CONFIGURATION_REQUIRED', 'CASE_CONFIGURATION_INVALID',
  'CASE_CATEGORY_INVALID', 'CASE_POLICY_CHANGED', 'CASE_POLICY_IMMUTABLE', 'CASE_CREATION_UNCERTAIN',
  'CASE_CHANNEL_DUPLICATE', 'CASE_CHANNEL_MISMATCH', 'CASE_CHANNEL_MISSING', 'CASE_CHANNEL_COLLISION',
  'CASE_OBSERVATION_UNTRUSTED', 'CASE_CONTEXT_UNTRUSTED', 'CASE_VERIFIER_REQUIRED', 'CASE_PROVISION_NOT_FOUND',
  'CASE_PROVISION_MISMATCH', 'CASE_STATE_CONFLICT']);
export const onboardingParkedCodes = Object.freeze(['SHUTTLE_CONTENT_REQUIRED', 'SHUTTLE_COPY_INVALID',
  'SHUTTLE_MESSAGE_UNCERTAIN', 'SHUTTLE_MESSAGE_UNTRUSTED', 'SHUTTLE_MESSAGE_OWNERSHIP',
  'SHUTTLE_MESSAGE_COLLISION', 'SHUTTLE_VERIFIER_REQUIRED', 'SHUTTLE_SCREEN_NOT_FOUND',
  'SHUTTLE_CASE_UNAVAILABLE', 'CASE_CHANNEL_ACL_MISMATCH']);
export const onboardingAlertParkedCodes = Object.freeze(['SHUTTLE_ALERT_UNCERTAIN', 'SHUTTLE_ALERT_MISSING',
  'SHUTTLE_ALERT_CHANGED', 'SHUTTLE_ALERT_NOT_FOUND', 'SHUTTLE_ALERT_VERIFIER_REQUIRED', 'STAFF_MENTION_UNAVAILABLE']);
export const caseIntakeParkedCodes = Object.freeze(['CASE_INTAKE_CORRUPT', 'CASE_FORM_CORRUPT', 'CASE_INTAKE_UNAVAILABLE', 'CASE_INTAKE_UNCERTAIN',
  'CASE_INTAKE_MESSAGE_MISSING', 'CASE_INTAKE_MESSAGE_CHANGED', 'CASE_INTAKE_VERIFIER_REQUIRED']);
export const caseReplyParkedCodes = Object.freeze(['CASE_REPLY_UNCERTAIN', 'CASE_REPLY_UNTRUSTED', 'CASE_REPLY_CONFIGURATION_INVALID', 'CASE_REPLY_CORRUPT',
  'CASE_REPLY_MESSAGE_MISSING', 'CASE_REPLY_WITHDRAWAL_UNCONFIRMED']);
export const automationParkedCodes = Object.freeze(['AUTOMATION_UNCERTAIN','AUTOMATION_CORRUPT','AUTOMATION_RECEIPT_INVALID']);
